dist: xenial

language: cpp

- os: linux

compiler:
  - clang
  - gcc

- os: linux
  install:
    - ./install-bazel.sh
  script:
    - bazel test -c dbg //...:all --test_output=all --action_env="GTEST_COLOR=1"

